name: integration

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  comment-on-pr:
  # commend on the original PR with the url for this action run
    runs-on: ubuntu-latest
    steps:
      - name: Get the PR number
        id: pr
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflow_run = context.payload.workflow_run
            const pr = workflow_run.pull_requests[0]
            console.log(`The PR is ${pr.number}`)
            return pr.number
      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = ${{ steps.pr.outputs.result }}
            github.issues.createComment({
              issue_number: pr,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The integration workflow requires approval: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })

  integration:
    runs-on: ubuntu-latest
    environment: my-environment
    steps:
      # This step checks the secrets available to the workflow
      - name: Check MY_SECRET
        run: |
          echo MY_SECRET is $MY_SECRET
          if [[ $MY_SECRET == *"environment"* ]]; then
            echo "This is the environment secret!"
          if [[ $MY_SECRET == *"repository"* ]]; then
            echo "This is the repository secret!"
          else
            echo "This is not the environment or repository secret!"
          fi
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Do stuff with the artifact
        run: cat artifact.txt